// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokRichtext, StoryblokAsset } from '../storyblok.d.ts';
export interface BasicPage {
  Body?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  component: "BasicPage";
  _uid: string;
  [k: string]: unknown;
}

export interface CardBlock {
  Title?: string;
  Overview_text?: string;
  Tags?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  Clock?: StoryblokAsset;
  Time?: string;
  component: "Card block";
  _uid: string;
  [k: string]: unknown;
}

export interface CardCaseStudy {
  title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  subtitle?: string;
  image?: string;
  component: "card_case_study";
  _uid: string;
  [k: string]: unknown;
}

export interface CardStatistics {
  title?: string;
  subtitle?: string;
  image?: StoryblokAsset;
  reference?: Reference[];
  component: "card_statistics";
  _uid: string;
  [k: string]: unknown;
}

export interface Carousel {
  cards?: (CaseStudyCard | ToolCard)[];
  component: "Carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface CaseStudies {
  title?: string;
  mainCard?: CaseStudyCard[];
  smallCards?: CaseStudyCard[];
  component: "CaseStudies";
  _uid: string;
  [k: string]: unknown;
}

export interface CaseStudyCard {
  title?: string;
  subTitle?: string;
  image?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "CaseStudyCard";
  _uid: string;
  [k: string]: unknown;
}

export interface Chart {
  component: "Chart";
  _uid: string;
  [k: string]: unknown;
}

export interface Code {
  Code?: unknown;
  component: "Code";
  _uid: string;
  [k: string]: unknown;
}

export interface ExpandableItem {
  label?: string;
  MegaMenu?: MegaMenu[];
  component: "expandableItem";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  columns?: FooterColumn[];
  component: "Footer";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterColumn {
  title?: string;
  links?: FooterColumnLink[];
  component: "FooterColumn";
  _uid: string;
  [k: string]: unknown;
}

export interface FooterColumnLink {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "FooterColumnLink";
  _uid: string;
  [k: string]: unknown;
}

export interface Formula {
  richText?: StoryblokRichtext;
  component: "Formula";
  _uid: string;
  [k: string]: unknown;
}

export interface FullWidthRichText {
  content?: StoryblokRichtext;
  component: "FullWidthRichText";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  title?: string;
  subTitle?: string;
  searchPlaceholderText?: string;
  image?: StoryblokAsset;
  component: "Header";
  _uid: string;
  [k: string]: unknown;
}

export interface HeaderInternalPages {
  breadcrumb?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  Header?: string;
  component: "Header internal pages";
  _uid: string;
  [k: string]: unknown;
}

export interface Hero {
  Globe: StoryblokAsset;
  Header: string;
  Sub_Header: string;
  component: "Hero";
  _uid: string;
  [k: string]: unknown;
}

export interface Home {
  component: "Home";
  _uid: string;
  [k: string]: unknown;
}

export interface HomePage {
  Header?: Header[];
  Middle?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  Bottom?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  component: "HomePage";
  _uid: string;
  [k: string]: unknown;
}

export interface Iframe {
  title: string;
  source: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  defaultHeight?: string;
  component: "Iframe";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageAndText {
  title?: string;
  subTitle?: string;
  image?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "ImageAndText";
  _uid: string;
  [k: string]: unknown;
}

export interface ImageText {
  Image?: StoryblokAsset;
  text?: string;
  component: "Image Text";
  _uid: string;
  [k: string]: unknown;
}

export interface Impact {
  title?: string;
  cards?: ImpactCard[];
  component: "Impact";
  _uid: string;
  [k: string]: unknown;
}

export interface ImpactCard {
  title?: string;
  subTitle?: string;
  icon?: "countries" | "experts" | "users";
  component: "ImpactCard";
  _uid: string;
  [k: string]: unknown;
}

export interface Landing {
  Block?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  Header?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  Content?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  Footer?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  component: "Landing";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  label?: string;
  component: "Link";
  _uid: string;
  [k: string]: unknown;
}

export interface MegaMenu {
  overview?: StoryblokRichtext;
  columns?: MegaMenuColumn[];
  component: "MegaMenu";
  _uid: string;
  [k: string]: unknown;
}

export interface MegaMenuColumn {
  title?: string;
  links?: Link[];
  component: "MegaMenuColumn";
  _uid: string;
  [k: string]: unknown;
}

export interface NavBar {
  logo?: StoryblokAsset;
  expandableItems?: ExpandableItem[];
  links?: Link[];
  component: "NavBar";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  logo?: StoryblokAsset;
  expandableItems?: ExpandableItem[];
  links?: Link[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface QuickLinks {
  title: string;
  subTitle: string;
  links?: QuickLinksItem[];
  component: "QuickLinks";
  _uid: string;
  [k: string]: unknown;
}

export interface QuickLinksItem {
  icon: "" | "RiCollageLine" | "RiShapeLine" | "RiGovernmentLine" | "RiFilePaperLine" | "RiGroupLine";
  link: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "QuickLinksItem";
  _uid: string;
  [k: string]: unknown;
}

export interface Quiz {
  questions?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  component: "Quiz";
  _uid: string;
  [k: string]: unknown;
}

export interface QuizAnswer {
  answerText?: string;
  helpText?: string;
  isCorrect?: boolean;
  component: "QuizAnswer";
  _uid: string;
  [k: string]: unknown;
}

export interface QuizQuestion {
  questionText?: string;
  answers?: (
    | BasicPage
    | CardBlock
    | CardCaseStudy
    | CardStatistics
    | Carousel
    | CaseStudies
    | CaseStudyCard
    | Chart
    | Code
    | ExpandableItem
    | Footer
    | FooterColumn
    | FooterColumnLink
    | Formula
    | FullWidthRichText
    | Header
    | HeaderInternalPages
    | Hero
    | Home
    | HomePage
    | Iframe
    | ImageAndText
    | ImageText
    | Impact
    | ImpactCard
    | Landing
    | Link
    | MegaMenu
    | MegaMenuColumn
    | NavBar
    | Page
    | QuickLinks
    | QuickLinksItem
    | Quiz
    | QuizAnswer
    | QuizQuestion
    | Reference
    | Reference
    | StatisticsAndText
    | StatisticsCard
    | StrategicPartner
    | StrategicPartners
    | Tag
    | TerryCode
    | Test
    | Test
    | TextModule
    | ToolCard
    | Unit
    | UnitChapter
    | UnitOverview
    | UnitSection
  )[];
  component: "QuizQuestion";
  _uid: string;
  [k: string]: unknown;
}

export interface Reference {
  websiteAuthor?: string;
  websiteTitle?: string;
  accessedDate?: string;
  yearPublished?: string;
  component: "reference";
  _uid: string;
  [k: string]: unknown;
}

export interface Reference {
  accessedDate?: string;
  yearPublished?: string;
  websiteAuthor?: string;
  websiteTitle?: string;
  websiteUrl?: string;
  component: "Reference";
  _uid: string;
  [k: string]: unknown;
}

export interface StatisticsAndText {
  title?: string;
  subTitle?: string;
  quotation?: string;
  reference?: Reference[];
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  cards?: StatisticsCard[];
  component: "StatisticsAndText";
  _uid: string;
  [k: string]: unknown;
}

export interface StatisticsCard {
  title?: string;
  subTitle?: string;
  image?: StoryblokAsset;
  reference?: Reference[];
  component: "StatisticsCard";
  _uid: string;
  [k: string]: unknown;
}

export interface StrategicPartner {
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  logo?: StoryblokAsset;
  component: "StrategicPartner";
  _uid: string;
  [k: string]: unknown;
}

export interface StrategicPartners {
  title?: string;
  partners?: (StrategicPartner | StrategicPartner)[];
  component: "StrategicPartners";
  _uid: string;
  [k: string]: unknown;
}

export interface Tag {
  title?: string;
  type?: "" | "primary" | "secondary" | "gray";
  component: "Tag";
  _uid: string;
  [k: string]: unknown;
}

export interface TerryCode {
  CODE?: unknown;
  component: "TerryCode";
  _uid: string;
  [k: string]: unknown;
}

export interface Test {
  component: "test";
  _uid: string;
  [k: string]: unknown;
}

export interface Test {
  component: "Test";
  _uid: string;
  [k: string]: unknown;
}

export interface TextModule {
  Sub_title?: string;
  Main_text?: string;
  component: "Text_module";
  _uid: string;
  [k: string]: unknown;
}

export interface ToolCard {
  title?: string;
  subTitle?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  icon?: "" | "calculator" | "dashboard" | "questionbank" | "report";
  component: "ToolCard";
  _uid: string;
  [k: string]: unknown;
}

export interface Unit {
  chapters?: (UnitChapter | UnitOverview)[];
  component: "Unit";
  _uid: string;
  [k: string]: unknown;
}

export interface UnitChapter {
  title?: string;
  subTitle?: string;
  sections?: UnitSection[];
  component: "UnitChapter";
  _uid: string;
  [k: string]: unknown;
}

export interface UnitOverview {
  title?: string;
  overviewRichText?: StoryblokRichtext;
  githubLink?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  readingTime?: string;
  component: "UnitOverview";
  _uid: string;
  [k: string]: unknown;
}

export interface UnitSection {
  title?: string;
  contentRichText?: StoryblokRichtext;
  component: "UnitSection";
  _uid: string;
  [k: string]: unknown;
}
