name: "Pull request and push integration (app)"
permissions:
  contents: read

on:
  push:
    branches: ["main"]
    paths:
      - ".storybook/**"
      - "public/**"
      - "src/**"
      - "*.js"
      - "*.json"
      - "*.mjs"
      - "*.ts"
  pull_request:
    branches: ["main"]
    paths:
      - ".storybook/**"
      - "public/**"
      - "src/**"
      - "*.js"
      - "*.json"
      - "*.mjs"
      - "*.ts"

jobs:
  audit-lint-build:
    runs-on: ubuntu-latest
    env:
      ASTRO_OUTPUT: static
      ASTRO_PREVIEW: false
      ASTRO_USE_LOCAL_DATA: true
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - run: npm run build
